version: '3.5'
services:
    web:
        build: ./webserver
        depends_on:
            - database
            - adminer
        volumes:
            - './www:/var/www/html:cached'
        ports:
            - '80:80'
            - '443:443'
        networks:
            - magentonet
    database:
        image: mysql:5.7
        command: --default-authentication-plugin=mysql_native_password --innodb-use-native-aio=0
        volumes:
            - 'magento_volume:/var/lib/mysql'
        environment:
            MYSQL_ROOT_PASSWORD: 'u73x5HipWT9XrmKe3UIXNwk1KBvjpIaBApzFHiyRCIYpaODBRRQ6uxUjo4lNYJ3VdhSqeCXETcL6erOGCABiiWyDl3z9hwJ0zvwi'
            MYSQL_DATABASE: 'magento_database'
            MYSQL_USER: 'magento_user'
            MYSQL_PASSWORD: 'mxpTfDbaUVxQWha5ZETA'
        restart: always
        networks: 
            - magentonet
    adminer:
        image: adminer
        restart: always
        networks: 
            - magentonet
        ports:
            - 8080:8080
networks: 
    magentonet:
volumes: 
    magento_volume:
