<h1>Teste ItHappens</h1>
<h2><?php echo $block->getMyName();?></h2>

<h3>Lista de Produtos</h3>
<table>
    <tr>
        <td>ID</td>
        <td>Nome</td>
    </tr>
    <?php foreach ($block->getAllProducts() as $produto): ?>
        <tr>
            <td><?php echo $produto->getId() ?></td>
            <td><?php echo $produto->getName() ?></td>
        </tr>
    <?php endforeach; ?>
</table>

<h3>Detalhe de Produto</h3>
<p>
    <?php $produto2 = $block->getProductDetail(); ?>
    <strong>ID:</strong>  <?php echo $produto2->getId() ?> <br />
    <strong>Nome:</strong> <?php echo $produto2->getName() ?> <br />
    <strong>Descrição:</strong>  <?php echo $produto2->getDescription() ?> <br />
    <strong>Preço:</strong>  <?php echo $produto2->getPrice() ?> <br />
    <strong>Estoque:</strong> <?php echo $block->getStockProduct($produto2->getId()) ?> <br />
    <strong>Imagem:</strong>  <img src="<?php echo $block->getUrlImage($produto2) ?>" />
</p>